service: oauth-middleware

frameworkVersion: "3.38.0"

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-2

functions:
  oauth:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'