service: oauth-middleware

frameworkVersion: "3.38.0"
useDotenv: true


provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-2
  profile: ${env:AWS_PROFILE}

functions:
  oauth:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'